version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    image: fe-link
    ports:
      - "3000:3000"
    command: /entrypoint.sh
    volumes:
      - ./${DEPENDENCY_GIT}/src:/${DEPENDENCY_GIT}/src
      - ./${DEPENDENCY_GIT}/types:/${DEPENDENCY_GIT}/types
      - ./${PROJECT_GIT}/src:/${PROJECT_GIT}/src
      - ./${PROJECT_GIT}/public:/${PROJECT_GIT}/public
      - ./${PROJECT_GIT}/config.d/config.js:/${PROJECT_GIT}/config.d/config.js
      - ./entrypoint.sh:/entrypoint.sh
    tty: true
